name: CD

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: wasm32-unknown-unknown

      - run: cargo generate-lockfile

      - uses: Swatinem/rust-cache@v2

      - name: Publish cargo package
        run: cargo login $CARGO_LOGIN_TOKEN && cargo publish
        env:
          CARGO_LOGIN_TOKEN: ${{ secrets.CARGO_LOGIN_TOKEN }}
