name: Test on different platforms

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - uses: actions/checkout@master

      - name: Install openssl on windows
        if: matrix.os == 'windows-latest'
        run: vcpkg integrate install; vcpkg install openssl:x64-windows
        env:
          VCPKG_ROOT: 'C:\vcpkg'

      - name: Build Win
        if: matrix.os == 'windows-latest'
        run: cargo build
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static
          VCPKG_ROOT: 'C:\vcpkg'

      - name: Run tests
        run: cargo test --verbose
